package com.myspace.sampleproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Line of Business")
	private java.lang.String lob;
	@org.kie.api.definition.type.Label(value = "Member Id")
	private java.lang.String memberId;
	@org.kie.api.definition.type.Label(value = "Message")
	private java.lang.String message;

	public Transaction() {
	}

	public java.lang.String getLob() {
		return this.lob;
	}

	public void setLob(java.lang.String lob) {
		this.lob = lob;
	}

	public java.lang.String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.lang.String memberId) {
		this.memberId = memberId;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public Transaction(java.lang.String lob, java.lang.String memberId,
			java.lang.String message) {
		this.lob = lob;
		this.memberId = memberId;
		this.message = message;
	}

}